// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdiNdkiKKeZq2YuyHKF4F47jL94joBwJs',
    appId: '1:667632067466:web:edf8f96e8a4a57656a5e73',
    messagingSenderId: '667632067466',
    projectId: 'hafiz-login-87b60',
    authDomain: 'hafiz-login-87b60.firebaseapp.com',
    storageBucket: 'hafiz-login-87b60.appspot.com',
    measurementId: 'G-252RCD0140',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4vOeM8ocS9CDe2oMzzKev8S5ZZw1Wii8',
    appId: '1:667632067466:android:e9011c555f88ee776a5e73',
    messagingSenderId: '667632067466',
    projectId: 'hafiz-login-87b60',
    storageBucket: 'hafiz-login-87b60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxlEsFL57hVWdgFoMZfAswblK3GTwPceQ',
    appId: '1:667632067466:ios:6ddc49bac91c13956a5e73',
    messagingSenderId: '667632067466',
    projectId: 'hafiz-login-87b60',
    storageBucket: 'hafiz-login-87b60.appspot.com',
    iosBundleId: 'com.example.loginbelajarHafiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxlEsFL57hVWdgFoMZfAswblK3GTwPceQ',
    appId: '1:667632067466:ios:6ddc49bac91c13956a5e73',
    messagingSenderId: '667632067466',
    projectId: 'hafiz-login-87b60',
    storageBucket: 'hafiz-login-87b60.appspot.com',
    iosBundleId: 'com.example.loginbelajarHafiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdiNdkiKKeZq2YuyHKF4F47jL94joBwJs',
    appId: '1:667632067466:web:f1e81b18e6bdbfa86a5e73',
    messagingSenderId: '667632067466',
    projectId: 'hafiz-login-87b60',
    authDomain: 'hafiz-login-87b60.firebaseapp.com',
    storageBucket: 'hafiz-login-87b60.appspot.com',
    measurementId: 'G-GXNF1BYWWQ',
  );
}
